version: '3.1'

services:
 vpe:
   container_name: vpe
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   ports:
     - 3389:3306
   environment:
     MYSQL_ROOT_PASSWORD: example
     MYSQL_DATABASE: vpe
     MYSQL_USER: user
     MYSQL_PASSWORD: password